#!/usr/bin/env python3
"""Generate the acceptance-gate rules from the gate matrix.

Phase 1 of the gate-matrix migration. The gates move out of the Makefile and
into `gates.mk`, which is generated from data rather than edited by hand. Make
stays the executor: the emitted text keeps `$(PYTHON)`, `$(RUN_DIR)` and every
other variable reference untouched, so expansion, ordering and overrides behave
exactly as before.

Two kinds of gate are emitted:

- a gate whose typed steps reproduce its commands (`tools/gate_render.py`
  proves this for all of them) is emitted from those steps; and
- a gate whose recipe embeds shell control flow is emitted verbatim, because
  the matrix does not model its loops and inventing a model would be a
  behaviour change disguised as a refactor.

The split is visible in the output, so what is still shell-only is obvious
rather than buried.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import gate_matrix
import gate_render


GATES_MK = gate_matrix.ROOT / "gates.mk"
GATES_JSON = gate_matrix.ROOT / "gates.json"


def to_data(matrix: dict) -> dict:
    """The authored form of the gate matrix.

    This is what a human edits once the migration completes: gate records
    rather than makefile text. A structured gate carries typed steps; a gate
    whose control flow is not yet modelled carries its recipe lines and says
    so, rather than pretending to a structure it does not have.
    """
    gates = []
    for gate in matrix["gates"]:
        record = {
            "name": gate["name"],
            "prerequisites": gate["prerequisites"],
            "variables": gate["variables"],
        }
        if "unstructured" in gate:
            record["unstructured"] = gate["unstructured"]
            record["recipe"] = gate["verbatim"]["recipe"]
        else:
            record["steps"] = gate["steps"]
        gates.append(record)
    return {"schema": 1,
            "press_profiles": matrix.get("press_profiles", {}),
            "product_runs": matrix.get("product_runs", {}),
            "shell_guards": matrix.get("shell_guards", {}),
            "gates": gates}


def from_data(data: dict) -> dict:
    """Rebuild the matrix shape the generator consumes from authored data."""
    gates = []
    for record in data["gates"]:
        gate = {
            "name": record["name"],
            "prerequisites": record.get("prerequisites", []),
            "variables": record.get("variables", {}),
            "steps": record.get("steps", []),
            "verbatim": {"declarations": [], "recipe": record.get("recipe", [])},
        }
        if "unstructured" in record:
            gate["unstructured"] = record["unstructured"]
        gates.append(gate)
    return {"schema": 1,
            "press_profiles": data.get("press_profiles", {}),
            "product_runs": data.get("product_runs", {}),
            "shell_guards": data.get("shell_guards", {}),
            "gates": gates, "segments": []}

HEADER = """\
# Generated by tools/gate_generate.py — do not edit.
#
# Acceptance gates for the Nokia DCT3 driver. Each gate runs a firmware session
# under MAME and checks the resulting trace. Regenerate with `make gates`.
#
# A gate marked "shell" below still carries its recipe verbatim: its control
# flow is not yet modelled by the gate matrix, so it is copied rather than
# rebuilt. Those are the remaining migration work.
"""


def _phony_lines(names, width: int = 78) -> list[str]:
    """Wrap `.PHONY` across continuations rather than one 190-target line.

    Recipes are left unwrapped because a break inside a quoted argument would
    change them, but `.PHONY` is a plain name list where wrapping is safe.
    """
    lines: list[str] = []
    current = ".PHONY:"
    for name in names:
        if len(current) + len(name) + 1 > width:
            lines.append(current + " \\")
            current = "\t" + name
        else:
            current += " " + name
    lines.append(current)
    return lines


def _declaration_lines(gate: dict) -> list[str]:
    """Target-specific variables first, then the rule and its prerequisites."""
    lines = []
    for name, value in gate["variables"].items():
        lines.append(f"{gate['name']}: {name}={value}")
    prerequisites = " ".join(gate["prerequisites"])
    lines.append(f"{gate['name']}:{' ' + prerequisites if prerequisites else ''}")
    return lines


def render_gate_rule(gate: dict) -> list[str]:
    lines = _declaration_lines(gate)
    if "unstructured" in gate:
        # Copied exactly. Re-wrapping a shell loop risks changing it.
        lines.extend(gate["verbatim"]["recipe"])
    else:
        # One command per line. A generated file may be wide; breaking a line
        # inside a quoted argument would not be.
        lines.extend(f"\t{command}" for command in gate_render.render_gate(gate))
    return lines


def _shell_guard_lines(guards: dict[str, str]) -> list[str]:
    """Emit the shell guards that gates share.

    A gate which rewrites the provisioned EEPROM restores the default however
    it exits. The guard is the function plus its trap; the `set -e` and any
    per-gate setup stay in the recipe so the variable composes.
    """
    if not guards:
        return []
    lines = [
        "# Shell guards shared by gates that rewrite provisioned state.",
        "#",
        "# Deferred (`=`), not immediate (`:=`). The guard names",
        "# $(EEPROM_BASENAME), which itself selects a filename from $(BIOS), and",
        "# gates set BIOS per target. Expanding at definition time would freeze",
        "# the default revision's EEPROM into every gate, so a v5.01 gate would",
        "# restore the v6.00 file.",
        "",
    ]
    for name, value in guards.items():
        lines.append(f"{name} = {value}")
    lines.append("")
    return lines


def _product_run_lines(runs: dict[str, str]) -> list[str]:
    """Emit the per-product run identity each gate selects.

    `PHONE` plus `BIOS` names one product and firmware revision. It was
    repeated inline in most gates and factored into a variable in one; naming
    all five the same way is what lets a family be compared across products
    without reading past the boilerplate.
    """
    if not runs:
        return []
    lines = ["# Product run identities: which handset and firmware a gate runs.", ""]
    width = max(len(name) for name in runs)
    for name, value in runs.items():
        lines.append(f"{name:<{width}} := {value}")
    lines.append("")
    return lines


def _press_profile_lines(profiles: dict[str, str]) -> list[str]:
    """Emit the named key press shapes the gate records refer to.

    Each name states its own values — `DCT3_PRESS_220_280` is a 220 ms press
    with a 280 ms gap. The names are deliberately descriptive rather than
    interpretive: why a given gate needs a particular shape is not recorded
    anywhere, and inventing labels like "standard" would assert a rationale
    that has not been established.
    """
    if not profiles:
        return []
    lines = ["# Key press shapes, named by value. A DURATION setting with no",
             "# paired GAP is a different shape and is left inline.", ""]
    width = max(len(name) for name in profiles)
    for name, value in profiles.items():
        lines.append(f"{name:<{width}} := {value}")
    lines.append("")
    return lines


def generate(matrix: dict) -> str:
    gates = matrix["gates"]
    structured = [g for g in gates if "unstructured" not in g]
    shell = [g for g in gates if "unstructured" in g]

    lines = [HEADER.rstrip("\n"), ""]
    lines.append(f"# {len(gates)} gates: {len(structured)} generated from typed "
                 f"steps, {len(shell)} copied verbatim (shell).")
    lines.append("")
    lines.extend(_shell_guard_lines(matrix.get("shell_guards", {})))
    lines.extend(_product_run_lines(matrix.get("product_runs", {})))
    lines.extend(_press_profile_lines(matrix.get("press_profiles", {})))
    lines.extend(_phony_lines(g["name"] for g in gates))
    lines.append("")

    for gate in gates:
        if "unstructured" in gate:
            lines.append(f"# shell: {gate['unstructured']}")
        lines.extend(render_gate_rule(gate))
        lines.append("")
    return "\n".join(lines)


def makefile_without_gates(matrix: dict) -> str:
    """The Makefile with every gate rule removed and `gates.mk` included.

    The include goes last: the first target in a makefile sets the default
    goal, and that must stay `help`.
    """
    kept: list[str] = []
    for segment in matrix["segments"]:
        if segment["kind"] == "gate":
            continue
        kept.extend(segment["lines"])

    # Removing rules leaves runs of blank lines behind. Collapse only runs of
    # three or more so ordinary spacing in the remaining text is untouched.
    collapsed: list[str] = []
    blanks = 0
    for line in kept:
        if line.strip():
            blanks = 0
            collapsed.append(line)
            continue
        blanks += 1
        if blanks <= 2:
            collapsed.append(line)

    while collapsed and not collapsed[-1].strip():
        collapsed.pop()

    collapsed += ["", "# Acceptance gates are generated; see tools/gate_generate.py.",
                  "include gates.mk", ""]
    return "\n".join(collapsed)


def verify_equivalence(original: dict, generated_text: str,
                       makefile_text: str) -> dict:
    """Require the generated rules to specify the same commands as the original.

    Compared as logical commands, per gate. This is the same contract
    `gate_render.py` enforces, applied to the emitted file rather than to the
    in-memory records.
    """
    combined = gate_matrix.extract(makefile_text + "\n" + generated_text)
    before = {g["name"]: gate_render.original_commands(g) for g in original["gates"]}
    after = {g["name"]: gate_render.original_commands(g) for g in combined["gates"]}

    problems: dict[str, str] = {}
    for name in sorted(set(before) | set(after)):
        if name not in after:
            problems[name] = "missing from generated rules"
        elif name not in before:
            problems[name] = "unexpected extra gate"
        elif before[name] != after[name]:
            problems[name] = "command sequence differs"

    declarations_before = {g["name"]: (sorted(g["prerequisites"]), g["variables"])
                           for g in original["gates"]}
    declarations_after = {g["name"]: (sorted(g["prerequisites"]), g["variables"])
                          for g in combined["gates"]}
    for name in sorted(set(declarations_before) & set(declarations_after)):
        if declarations_before[name] != declarations_after[name]:
            problems.setdefault(name, "prerequisites or variables differ")

    return {"gates": len(before), "problems": problems}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--makefile", type=pathlib.Path, default=None)
    parser.add_argument("--output", type=pathlib.Path, default=GATES_MK)
    parser.add_argument("--write-makefile", action="store_true",
                        help="also rewrite the Makefile with the gates removed")
    parser.add_argument("--check", action="store_true",
                        help="verify only; write nothing")
    parser.add_argument("--emit-data", action="store_true",
                        help="also write gates.json, the authored gate records")
    parser.add_argument("--from-data", action="store_true",
                        help="generate from gates.json instead of the makefile")
    arguments = parser.parse_args()

    source = arguments.makefile or gate_matrix.gate_source()
    text = source.read_text()

    # Trimming only makes sense while the gates still live in the Makefile.
    # Once they have moved, `makefile_without_gates` would be handed gates.mk
    # and would write its non-gate remainder over the Makefile.
    migrated = source.resolve() != gate_matrix.MAKEFILE.resolve()
    if arguments.write_makefile and migrated:
        print(f"FAIL - gates already live in {source.name}; "
              f"the Makefile no longer contains gate rules to remove")
        return 2

    if arguments.from_data:
        import json as _json
        matrix = from_data(_json.loads(GATES_JSON.read_text()))
    else:
        matrix = gate_matrix.check_round_trip(text)
    generated = generate(matrix)
    trimmed = None if migrated else makefile_without_gates(matrix)

    if arguments.from_data:
        # Authored records carry no verbatim recipe for structured gates, so
        # the per-gate command comparison has nothing to compare against. The
        # meaningful contract here is that the data regenerates the committed
        # rules. Under --check that must already hold; otherwise this is the
        # step that writes the update.
        if arguments.check:
            if GATES_MK.exists() and generated != GATES_MK.read_text():
                print("FAIL - gates.mk is stale; run `make gates` to regenerate")
                return 1
            print(f"gate generate: gates.json regenerates gates.mk exactly "
                  f"({len(matrix['gates'])} gates)")
            return 0
        arguments.output.write_text(generated)
        print(f"gate generate: wrote {arguments.output.name} from gates.json "
              f"({len(matrix['gates'])} gates)")
        return 0

    result = verify_equivalence(matrix, generated,
                                trimmed if trimmed is not None else "")
    if result["problems"]:
        print(f"FAIL - {len(result['problems'])} gates differ after generation")
        for name, problem in list(result["problems"].items())[:10]:
            print(f"    {name}: {problem}")
        return 1

    if not arguments.check:
        arguments.output.write_text(generated)
        if arguments.emit_data:
            import json as _json
            GATES_JSON.write_text(
                _json.dumps(to_data(matrix), indent=2) + "\n")
        if arguments.write_makefile:
            gate_matrix.MAKEFILE.write_text(trimmed)

    if trimmed is not None:
        saved = len(text.split("\n")) - len(trimmed.split("\n"))
        print(f"gate generate: {result['gates']} gates reproduce their commands; "
              f"Makefile loses {saved} lines")
    else:
        print(f"gate generate: {result['gates']} gates reproduce their commands "
              f"from {source.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
