-- Physical shutdown and PWRONX restart; no charger or firmware state writes.
local source = debug.getinfo(1, 'S').source:sub(2)
dofile(assert(source:match('^(.*[/])')) .. 'noki6210_staged_observe.lua')
local machine = manager.machine
local cpu = assert(machine.devices[':maincpu'])
cpu.debug:bpset(0x4fad30, nil,
    'logerror "6210_keypad_decoded: key=%02x\\n",r0;g')
local power = assert(machine.ioport.ports[':PWR'].fields['Power'])
local function at(when)
    return emu.wait(when - machine.time:as_double())
end
local input = coroutine.create(function()
    assert(at(20))
    machine.screens[':screen']:snapshot('6210_power_idle.png')
    assert(at(25))
    machine:logerror('6210_power_physical: action=shutdown_press\n')
    power:set_value(1)
    assert(emu.wait(4))
    power:set_value(0)
    machine:logerror('6210_power_physical: action=shutdown_release\n')
    assert(at(33))
    machine.screens[':screen']:snapshot('6210_power_off.png')
    -- Exceed the previous 49-second reload window while the rails are off.
    assert(at(90))
    -- Re-arm passive log caps for the second own-upload observation.
    machine.debugger:command('do temp5=0;do temp6=0;do temp9=0')
    machine:logerror('6210_power_physical: action=restart_press\n')
    power:set_value(1)
    assert(emu.wait(2))
    power:set_value(0)
    machine:logerror('6210_power_physical: action=restart_release\n')
    assert(at(107))
    machine.screens[':screen']:snapshot('6210_power_restarted.png')
    assert(at(110))
    local menu = assert(machine.ioport.ports[':COL.1'].fields['Left Softkey / Menu'])
    machine:logerror('6210_power_physical: action=menu\n')
    menu:set_value(1)
    assert(emu.wait(0.15))
    menu:set_value(0)
    assert(at(113))
    machine.screens[':screen']:snapshot('6210_power_menu.png')
end)
_G.noki6210_power_cycle_input = input
assert(coroutine.resume(input))
